version: '3.4'

services:
  json-server:
    image: node:13.10.1-alpine3.10
    working_dir: /workspace
    volumes:
      - ./node_modules:/workspace/node_modules
      - ./package.json:/workspace/package.json
      - ./src/json-server:/workspace/json-server
    stdin_open: true
    tty: true
    command: yarn start
    ports:
      - 13000:13000
    restart: always
